Add item requests
savannavea/java-shareit pull request #3
Opened 2023-09-17 17:23 UTC by savannavea

2023-09-19 19:25 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-19 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Reservation not found");
В лог и сообщения об ошибках давай больше подробностей/деталей, ведь потом тебе по этим сообщениям нужно будет понимать что случилось...

2023-09-19 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    private User getUserOrElseThrow(Long userId) {
Не подключай репозиторий пользователей, подключай сервис.
А в сервисе если нужно сделай такой метод.

А так ты метод `getUserOrElseThrow` вынуждена создавать в каждом сервисе...

2023-09-19 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        List<ItemRequestDto> result = new ArrayList<>();
Можно переписать используя `collect`

```
    public List<ItemRequestDto> getAllByUserId(Long userId) {
        getUserOrElseThrow(userId);

        return itemRequestRepository.findItemRequestByRequesterId(userId).stream()
                                    .map(this::addItemsToRequest)
                                    .collect(Collectors.toList());
    }
```

В методе ниже тоже можно - сделай это самостоятельно.

2023-09-20 18:34 UTC, savannavea commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Reservation not found");
Привет. Дописала сообщение об ошибке, дальше пролистала, вроде в остальных подробнее написано))

2023-09-20 18:35 UTC, savannavea commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    private User getUserOrElseThrow(Long userId) {
Подредактировала, подключила везде сервисы)

2023-09-20 18:35 UTC, savannavea commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        List<ItemRequestDto> result = new ArrayList<>();
переписала

2023-09-20 18:55 UTC, FanaticFiz approved these changes

2023-09-21 10:02 UTC, merged