Add docker
savannavea/java-shareit pull request #4
Opened 2023-09-25 18:08 UTC by savannavea

2023-09-26 19:14 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-26 19:14 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Если методы делают одно и тоже, то можно объединить их в один.
Можно прописать несколько классов в одной аннотации, найди как это сделать.

2023-09-26 19:14 UTC, FanaticFiz commented on pom.xml
> +	</modules>
В родительском `pom` файле, лучше не указывать зависимостей, ведь все они будут унаследованы дочерними...

2023-09-26 19:14 UTC, FanaticFiz commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://db:5432/shareit
Начнешь делать дипломную работу, не приходи ко мне без свойств написанных в YAML формате! )))

2023-09-28 10:25 UTC, savannavea commented on gateway/src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Объединила))

2023-09-28 10:26 UTC, savannavea commented on pom.xml
> +	</modules>
Исправила

2023-09-28 10:26 UTC, savannavea commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://db:5432/shareit
Ок!)))

2023-09-28 19:20 UTC, FanaticFiz approved these changes

2023-10-04 09:36 UTC, merged